name: note_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  get_storage: 2.0.3
  simple_rich_text: 2.0.49
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/cuate.png
    - assets/images/rafiki.png
  fonts: 
    - family: Nunito
      fonts: 
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 800
  uses-material-design: true

